### PR TITLE
fix(frontend): public pages extra rendering

### LINKED ISSUE #215: 🐛 [BUG] - UI freeze for public after authentication
### Description

When we open public pages we can notice a rendering issue (login, register, reset pages)

<video src ="https://github.com/user-attachments/assets/2c884743-a29a-4e30-b035-17b2ab6c2e2f" />

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
The main motivation of this update is to fix public pages extra rendering.

Before the update :
<video src ="https://github.com/user-attachments/assets/2c884743-a29a-4e30-b035-17b2ab6c2e2f" />

After the update :
<video src="https://github.com/user-attachments/assets/27dac394-eb0b-404d-a838-c33bdc6ad432" />

Fixes #215

# Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by IkbelTalebHssan — COMMENTED** [review]
Hi @yassinedorbozgithub ,
I can still see the issue from my end.. The rendering is faster then before but it still shows the login page after login.

**Comment by yassinedorbozgithub** [comment]
> Hi @yassinedorbozgithub , I can still see the issue from my end.. The rendering is faster then before but it still shows the login page after login.

Hi @IkbelTalebHssan, i will double check from my end to identify if something is missed in the added logic

**Comment by IkbelTalebHssan** [comment]
> > Hi @yassinedorbozgithub , I can still see the issue from my end.. The rendering is faster then before but it still shows the login page after login.
> 
> Hi @IkbelTalebHssan, i will double check from my end to identify if something is missed in the added logic

Hi again @yassinedorbozgithub ,
After rebuilding the project everything works fine and the issue is resolved :pray: 
Nice work :rocket:

**Comment by yassinedorbozgithub** [comment]
> > > Hi @yassinedorbozgithub , I can still see the issue from my end.. The rendering is faster then before but it still shows the login page after login.
> > 
> > 
> > Hi @IkbelTalebHssan, i will double check from my end to identify if something is missed in the added logic
> 
> Hi again @yassinedorbozgithub , After rebuilding the project everything works fine and the issue is resolved 🙏 Nice work 🚀

Hi @IkbelTalebHssan, thank you for the positive feedback's :raised_hands:

**Review by medchedli — APPROVED** [review]

**Pull request merged**
