### PR TITLE
update(docker): remove duplicated NEXT_PUBLIC_API_ORIGIN environment variable

### LINKED ISSUE #28: 🤔 [ISSUE] - Duplicated NEXT_PUBLIC_API_ORIGIN env variable
### Description

The **env.example** file situated under the **/docker** directory contains a duplicated **NEXT_PUBLIC_API_ORIGIN** keys.

### Reproduction steps

```bash
1. Go to Hexabot root directory
2. Open /docker directory
3. Open .env.example file
4. See that NEXT_PUBLIC_API_ORIGIN variable is duplicated
```

### Logs

_No response_

### Browsers

Chrome

### OS

Linux

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation

The env.example file situated under the /docker directory contains a duplicated NEXT_PUBLIC_API_ORIGIN keys.

Fixes #28

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marrouchi — CHANGES_REQUESTED** [review]
Thanks

Can you please update the other vars to include the API port : 


```
# Frontend (Next.js)
APP_FRONTEND_PORT=8080
NEXT_PUBLIC_API_ORIGIN=http://${APP_DOMAIN}:${API_PORT}
NEXT_PUBLIC_SSO_ENABLED=false

# Widget
APP_WIDGET_PORT=5173
REACT_APP_WIDGET_API_URL=http://${APP_DOMAIN}:${API_PORT}
REACT_APP_WIDGET_CHANNEL=offline
REACT_APP_WIDGET_TOKEN=token123
```

**Comment by yassinedorbozgithub** [comment]
Hi @marrouchi, the recommended updates are applied :heavy_check_mark:

**Review by medtaher123 — APPROVED** [review]

**Review by medtaher123 — COMMENTED** [review]
We could replace `MONGO_URI=mongodb://dev_only:dev_only@mongo:27017/` with `MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/` for better flexibility

**Review by marrouchi — APPROVED** [review]
🥳

**Pull request merged**
